# Site settings
title: Журнал науки и техники
email: journal@factum.me
description: "Журнал науки и техники"
baseurl: "/journal"
url: "http://factum.me"
twitter_username: jekyllrb_
github_username:  jekyll_

# Build settings
markdown: kramdown
permalink: pretty
