# Site settings
title: Журнал науки и техники
email: journal@factum.me
description: "Журнал науки и техники"
baseurl: "/journal"
url: "http://factum.me"
twitter_username: FactumMeJournal
facebook_username: FactumMeJournal
vk_username: factummejournal
github_username: factum-me/journal

# Build settings
markdown: kramdown
permalink: pretty
