# Site settings
title: Журнал науки и техники
email: journal@factum.me
description: "Журнал науки и техники"
baseurl: "/journal"
url: "http://factum.me"
twitter_username: FactumMeJournal
github_username: https://github.com/factum-me/journal

# Build settings
markdown: kramdown
permalink: pretty
