# Site settings
title: Журнал науки и техники
email: factummejournal@denisx.ru
description: "Журнал науки и техники"
baseurl: "/journal.github.io"
url: "http://factum-me.github.io"
twitter_username: jekyllrb_
github_username:  jekyll_

# Build settings
markdown: kramdown
permalink: pretty
