# Site settings
title: Журнал науки и техники
email: factummejournal@denisx.ru
description: "Журнал науки и техники"
baseurl: "/"
url: "https://factum.me"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
